server {
    listen 80;
    root /usr/share/nginx/html;
    index pool-lanes/index.html;

    location /pool-lanes/ {
        try_files $uri $uri/ /pool-lanes/index.html;
    }

    location = / {
        return 301 /pool-lanes/;
    }
}
